server:
  port: 8060
  servlet:
    context-path: /
    encoding:
      enabled: true
      force: true
      charset: UTF-8

#  datasource:
#    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
#    url: jdbc:p6spy:mysql://localhost:3306/blog_demo
#    username: root
#    password: 1234
#
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/security_demo?serverTime=Asia/Seoul
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
  devtools:
    livereload:
      enabled: true
  security:
    user:
      name: user
      password: 1234

